import React, { createContext, useState, useContext, useEffect, useMemo, useCallback } from 'react';

const translations = {
  en: {
    main_menu: 'MAIN MENU',
    menu_dispatch: 'Dispatch Queue',
    menu_radar: 'Global Radar',
    menu_inventory: 'Inventory',
    menu_analytics: 'Analytics',
    menu_settings: 'Settings',
    sign_out: 'Sign Out',
    close: 'Close',

    save_btn: 'Save Changes',
    processing: 'PROCESSING...',
    settings_title: 'System Settings',
    tab_profile: 'Profile',
    tab_appearance: 'Appearance',
    tab_notifications: 'Notifications',
    tab_security: 'Security',
    lang_label: 'Interface Language',
    theme_label: 'Theme',
    theme_light: 'Light',
    theme_dark: 'Dark (Default)',
    full_name: 'Full Name',
    system_role: 'System Role',
    role_change_info: 'Role change is restricted to administrators.',
    email_label: 'Email Address',
    phone_label: 'Phone Number',
    upload_photo: 'Upload Photo',
    remove_photo: 'Remove',
    saved_success: 'Changes saved successfully!',

    total_nodes: 'Active Nodes',
    fleet_transit: 'In Transit',
    critical_alerts: 'Critical Alerts',
    system_status: 'System Status',
    action_required: 'Action Required',
    Operational: 'Operational',
    trucks: 'Trucks',
    active: 'Active',

    global_feed: 'Global Incidents',
    network_anomalies: 'Network anomalies and active routes.',
    select_node: 'Select a node on the map to view details.',
    node_telemetry: 'Node Telemetry',
    main_hub_desc: 'Main distribution center. All vehicles are dispatched from this location.',
    main_hub_desc_strong: 'Central Distribution Hub.',
    main_hub_desc_sub: 'Origin point for all fleets.',
    active_request: 'Active Request / Cargo',
    units_expected: 'units expected',
    crisis_protocol: 'Crisis Protocol',
    driver_delayed_msg: 'Driver reported a critical issue on the route. Fleet is halted.',
    low_stock_msg: 'Facility stock has dropped below critical levels (20%). High risk of supply failure.',
    reroute_backup: 'Reroute Nearest Backup',
    mark_resolved: 'Mark Issue as Resolved',
    Alert: 'Alert',

    available_orders: 'Available Orders',
    truck_manifest: 'Truck Manifest (AI-1020)',
    review_route: 'Review route and capacity',
    payload_capacity: 'PAYLOAD CAPACITY',
    route_stops: 'Route Stops',
    truck_empty: 'The truck is empty',
    add_orders_msg: 'Add orders from the queue to start routing.',
    add_to_truck: 'Add to Truck',
    no_orders: 'No orders available.',
    remove: 'Remove',
    confirm_dispatch: 'Confirm & Dispatch Fleet',
    cannot_dispatch: 'Cannot Dispatch (Overloaded)',
    units: 'Units',
    of: 'of',

    dispatch_queue: 'Dispatch Queue',
    add_queue: 'ADD TO QUEUE',
    cargo_manifest: 'Cargo Manifest',
    dest_stock: 'Destination Stock Level',
    req_units: 'Requested',
    deficit: 'Deficit to deliver',
    dispatch_fleet: 'Dispatch Vehicle',
    mark_delivered: 'Mark Delivered ✔',
    cargo: 'Cargo',

    cargo_type: 'CARGO TYPE',
    delivery_address: 'DELIVERY ADDRESS',
    units_req_label: 'UNITS REQ.',
    urgency: 'URGENCY',
    submit_request: 'SUBMIT REQUEST',

    login_title: 'DispatchX', 
    login_id: 'LOGIN ID',
    password: 'PASSWORD',
    login_btn: 'LOGIN',
    register_btn: 'REGISTER',
    login_hints: 'Try credentials: admin/123, disp/123, client/123, driver/123',
    create_id: 'Create an ID',
    enter_id: 'Enter ID',
    create_password: 'Create a Password',
    enter_password: 'Enter Password',
    your_role: 'YOUR ROLE',
    role_client: 'Client (Request Items)',
    role_dispatcher: 'Supplier/Dispatcher (Manage Deliveries)',
    link_login: 'Already have an account? Login',
    link_register: "Don't have an account? Register",
    auth_subtitle: 'Authentication System', 
    error_required: 'This field is required',
    error_password_length: 'Password must be at least 6 characters long.',
    error_short_pass: 'Password too short',

    notifications_title: 'Notifications',
    clear_all: 'Clear all',
    no_notifications: 'No notifications yet',
    notif_msg_1: 'Critical deficit: Lviv Hub urgently needs 150 units of "Ammunition".',
    notif_msg_2: 'Warning: Transport delay on Kyiv-Rivne route due to weather conditions.',
    notif_title: 'Notification Preferences',
    notif_desc: 'Configure alerts for urgent requests and demand changes.',
    notif_email: 'Email Alerts (Daily Summary)',
    notif_sms: 'SMS Alerts (Critical Only)',
    notif_push: 'Push Notifications',
    push_enabled_msg: 'Push notifications are now enabled!',
    push_blocked_msg: 'Please allow notifications in your browser settings.',

    sec_title: 'Account Security',
    sec_desc: 'Manage authentication and access credentials.',
    sec_password: 'Change Password',
    sec_2fa: 'Two-Factor Authentication (2FA)',
    two_factor_msg: '2FA activated. SMS verification required on next login.',
    sec_current_password: 'Current Password',
    sec_new_password: 'New Password',
    sec_update: 'Update',

    inventory_title: 'Global Inventory',
    inventory_subtitle: 'Manage and monitor real-time stock across all hubs.',
    inventory_subtitle_manage: 'Manage and monitor real-time stock across all hubs.',
    inventory_subtitle_view: 'View available supplies in our network.',
    add_shipment: ' Add Shipment',
    search_placeholder: 'Search by SKU or Name...',
    all_categories: 'All Categories',
    col_sku: 'SKU & NAME',
    col_location: 'LOCATION',
    col_status: 'STATUS',
    col_stock: 'STOCK LEVEL',
    col_action: 'ACTION',
    edit: 'Edit',
    status_in_stock: 'IN STOCK',
    status_low_stock: 'LOW STOCK',
    status_out_of_stock: 'OUT OF STOCK',

    modal_update_stock: 'Update Stock Quantity',
    modal_add_shipment: 'Add New Shipment',
    modal_product_name: 'Product Name',
    modal_warehouse: 'Warehouse Location',
    modal_category: 'Category',
    modal_max_capacity: 'Max Capacity (Units)',
    modal_current_qty: 'Current Quantity (Units)',
    modal_updating_sku: 'Updating SKU',
    cancel: 'Cancel',

    analytics_title: 'Performance Analytics',
    analytics_subtitle: 'Overview of fleet efficiency and supply chain health.',
    on_time_delivery: 'ON-TIME DELIVERY',
    compared_last_month: 'Compared to last month',
    active_incidents: 'ACTIVE INCIDENTS',
    requiring_attention: 'Requiring dispatcher attention',
    total_volume: 'TOTAL VOLUME MOVED',
    across_hubs: 'Across all hubs this week',
    weekly_dispatch: 'Weekly Fleet Dispatch Volume',
    recent_risks: 'Recent Risk Factors',
    on_time: 'On Time',
    delayed: 'Delayed',
    status_resolved: 'RESOLVED',
    status_active: 'ACTIVE',

    issue: 'Issue',
    'Border Delay': 'Border Delay',
    'Customs Check': 'Customs Check',
    'Vehicle Breakdown': 'Vehicle Breakdown',

    'All': 'All',
    'Medicine': 'Medicine',
    'Food': 'Food',
    'Food Rations': 'Food Rations',
    'Water': 'Clean Water',
    'Clean Water': 'Clean Water',
    'Generators': 'Generators',
    'Ammunition': 'Ammunition',
    'Equipment': 'Equipment',
    'Fuel': 'Fuel',
    'Thermal Blankets': 'Thermal Blankets',
    'Surgical Supplies': 'Surgical Supplies',
    'Other': 'Other',

    'Normal': 'Normal',
    'High Priority': 'High Priority',
    'Critical Alert': 'Critical Alert',

    'PENDING': 'PENDING',
    'IN_TRANSIT': 'IN TRANSIT',
    'DELIVERED': 'DELIVERED',
    'DELAYED': 'DELAYED',
    'DRAFT': 'DRAFT',

    driver_view: 'Driver View',
    current_route: 'Current Route',
    report_issue: 'Report Issue',
    mark_arrived: 'Mark as Arrived',

    // Нові ключі для ClientDashboard
    create_order: 'Create Order',
    my_active_orders: 'My Active Orders',
    live_supply_catalog: 'Live Supply Catalog',
    select_items_to_start: 'Select items to start order configuration',
    search_catalog: 'Search catalog...',
    available_label: 'AVAILABLE',
    hub_label: 'HUB',
    empty_label: 'EMPTY',
    order_config: 'Order Configuration',
    finalize_delivery: 'Finalize delivery details',
    please_select_item: 'Please select an item',
    click_any_card: 'Click on any card in the catalog to begin',
  },

  uk: {
    main_menu: 'ГОЛОВНЕ МЕНЮ',
    menu_dispatch: 'Черга відправок',
    menu_radar: 'Глобальний Радар',
    menu_inventory: 'Склад',
    menu_analytics: 'Аналітика',
    menu_settings: 'Налаштування',
    sign_out: 'Вийти',
    close: 'Закрити',

    step_processing: 'Обробка',
step_dispatched: 'Відправлено',
destination: 'Призначення',
live_tracking: 'Відстеження',
contact_driver: 'Зв\'язок з водієм',
no_active_orders: 'Наразі немає активних замовлень.',

    save_btn: 'Зберегти зміни',
    processing: 'ОБРОБКА...',
    settings_title: 'Налаштування Системи',
    tab_profile: 'Профіль',
    tab_appearance: 'Зовнішній вигляд',
    tab_notifications: 'Сповіщення',
    tab_security: 'Безпека',
    lang_label: 'Мова інтерфейсу',
    theme_label: 'Тема оформлення',
    theme_light: 'Світла',
    theme_dark: 'Темна (За замовчуванням)',
    full_name: "Повне ім'я",
    system_role: 'Роль у системі',
    role_change_info: 'Зміна ролі доступна лише адміністраторам.',
    email_label: 'Електронна пошта',
    phone_label: 'Номер телефону',
    upload_photo: 'Завантажити фото',
    remove_photo: 'Видалити',
    saved_success: 'Зміни успішно збережено!',

    total_nodes: 'Активні вузли',
    fleet_transit: 'Транспорт у дорозі',
    critical_alerts: 'Критичні статуси',
    system_status: 'Статус системи',
    action_required: 'Потрібна дія',
    Operational: 'Працює стабільно',
    trucks: 'Вантажівок',
    active: 'Активних',

    global_feed: 'Стрічка подій',
    network_anomalies: 'Аномалії мережі та активні маршрути.',
    select_node: 'Оберіть вузол на карті для деталей.',
    node_telemetry: 'Телеметрія вузла',
    main_hub_desc: 'Головний розподільчий центр. Увесь транспорт відправляється звідси.',
    main_hub_desc_strong: 'Центральний розподільчий хаб.',
    main_hub_desc_sub: 'Початкова точка для всіх рейсів.',
    active_request: 'Активний запит / Вантаж',
    units_expected: 'одиниць очікується',
    crisis_protocol: 'Кризовий протокол',
    driver_delayed_msg: 'Водій повідомив про критичну проблему на маршруті. Рейс зупинено.',
    low_stock_msg: 'Запаси впали нижче критичного рівня (20%). Високий ризик перебоїв у постачанні.',
    reroute_backup: 'Перенаправити резервний транспорт',
    mark_resolved: 'Позначити проблему як вирішену',
    Alert: 'Тривога',

    available_orders: 'Доступні замовлення',
    truck_manifest: 'Маніфест вантажівки (AI-1020)',
    review_route: 'Перегляд маршруту та вантажу',
    payload_capacity: 'ВАНТАЖОПІДЙОМНІСТЬ',
    route_stops: 'Зупинки маршруту',
    truck_empty: 'Вантажівка порожня',
    add_orders_msg: 'Додайте замовлення з черги для побудови маршруту.',
    add_to_truck: 'Додати у вантажівку',
    no_orders: 'Немає доступних замовлень.',
    remove: 'Видалити',
    confirm_dispatch: 'Підтвердити та відправити',
    cannot_dispatch: 'Неможливо відправити (Перевантаження)',
    units: 'Одиниць',
    of: 'з',

    dispatch_queue: 'Черга відправок',
    add_queue: '+ ДОДАТИ В ЧЕРГУ',
    cargo_manifest: 'Вантажний маніфест',
    dest_stock: 'Рівень запасів',
    req_units: 'Запитано',
    deficit: 'Дефіцит для доставки',
    dispatch_fleet: 'Відправити транспорт',
    mark_delivered: 'Позначити доставленим ✔',
    cargo: 'Вантаж',

    cargo_type: 'ТИП ВАНТАЖУ',
    delivery_address: 'АДРЕСА ДОСТАВКИ',
    units_req_label: 'КІЛЬКІСТЬ',
    urgency: 'ТЕРМІНОВІСТЬ',
    submit_request: 'ВІДПРАВИТИ ЗАПИТ',

    exit_route: 'Вийти',
fleet_status: 'СТАТУС ТРАНСПОРТУ',
active_route: 'АКТИВНИЙ МАРШРУТ',
stops_left: 'зупинок залишилось',
stop_label: 'ЗУПИНКА',
destination_address: 'АДРЕСА ПРИЗНАЧЕННЯ',
quantity: 'КІЛЬКІСТЬ',
confirm_unload: 'ПІДТВЕРДИТИ РОЗВАНТАЖЕННЯ',
report_delay_issue: 'Повідомити про затримку / проблему',

    login_title: 'DispatchX', 
    login_id: 'ЛОГІН',
    password: 'ПАРОЛЬ',
    login_btn: 'УВІЙТИ',
    register_btn: 'ЗАРЕЄСТРУВАТИСЯ',
    login_hints: 'Спробуйте: admin/123, disp/123, client/123, driver/123',
    create_id: 'Створіть логін',
    enter_id: 'Введіть логін',
    create_password: 'Створіть пароль',
    enter_password: 'Введіть пароль',
    your_role: 'ВАША РОЛЬ',
    role_client: 'Клієнт (Замовник)',
    role_dispatcher: 'Диспетчер (Управління)',
    link_login: 'Вже є акаунт? Увійти',
    link_register: 'Немає акаунту? Зареєструватися',
    auth_subtitle: 'Система Автентифікації', 

    error_required: 'Це поле обов\'язкове',
    error_password_length: 'Пароль має містити мінімум 6 символів.',
    error_short_pass: 'Пароль надто короткий',

    notifications_title: 'Сповіщення',
    clear_all: 'Очистити все',
    no_notifications: 'Немає нових сповіщень',
    notif_msg_1: 'Критичний дефіцит: Lviv Hub терміново потребує 150 од. "Амуніція".',
    notif_msg_2: 'Увага: Затримка транспорту на маршруті Київ-Рівне через погодні умови.',
    notif_title: 'Налаштування сповіщень',
    notif_desc: 'Налаштуйте сповіщення для термінових запитів та змін попиту.',
    notif_email: 'Email сповіщення (Щоденний звіт)',
    notif_sms: 'SMS сповіщення (Тільки критичні)',
    notif_push: 'Push-сповіщення у браузері',
    push_enabled_msg: 'Push-сповіщення успішно увімкнено!',
    push_blocked_msg: 'Будь ласка, дозвольте сповіщення у налаштуваннях браузера.',

    sec_title: 'Безпека акаунту',
    sec_desc: 'Управління автентифікацією та обліковими даними.',
    sec_password: 'Змінити пароль',
    sec_2fa: 'Двофакторна автентифікація (2FA)',
    two_factor_msg: '2FA активовано. При наступному вході знадобиться SMS-код.',
    sec_current_password: 'Поточний пароль',
    sec_new_password: 'Новий пароль',
    sec_update: 'Оновити',

    inventory_title: 'Глобальний склад',
    inventory_subtitle: 'Управління та моніторинг запасів у реальному часі.',
    inventory_subtitle_manage: 'Управління та моніторинг запасів у реальному часі.',
    inventory_subtitle_view: 'Перегляд доступних запасів у нашій мережі.',
    add_shipment: ' Додати відправлення',
    search_placeholder: 'Пошук за SKU або назвою...',
    all_categories: 'Всі категорії',
    col_sku: 'SKU ТА НАЗВА',
    col_location: 'РОЗТАШУВАННЯ',
    col_status: 'СТАТУС',
    col_stock: 'РІВЕНЬ ЗАПАСІВ',
    col_action: 'ДІЯ',
    edit: 'Редагувати',
    status_in_stock: 'В НАЯВНОСТІ',
    status_low_stock: 'МАЛО',
    status_out_of_stock: 'ВІДСУТНІЙ',

    modal_update_stock: 'Оновити кількість запасів',
    modal_add_shipment: 'Додати нове відправлення',
    modal_product_name: 'Назва продукту',
    modal_warehouse: 'Склад',
    modal_category: 'Категорія',
    modal_max_capacity: 'Максимальна ємність (одиниць)',
    modal_current_qty: 'Поточна кількість (одиниць)',
    modal_updating_sku: 'Оновлення SKU',
    cancel: 'Скасувати',

    analytics_title: 'Аналітика продуктивності',
    analytics_subtitle: 'Огляд ефективності флоту та стану ланцюга постачання.',
    on_time_delivery: 'ВЧАСНА ДОСТАВКА',
    compared_last_month: 'Порівняно з минулим місяцем',
    active_incidents: 'АКТИВНІ ІНЦИДЕНТИ',
    requiring_attention: 'Потребують уваги диспетчера',
    total_volume: 'ЗАГАЛЬНИЙ ОБСЯГ',
    across_hubs: 'По всіх хабах цього тижня',
    weekly_dispatch: 'Тижневий обсяг відправлень',
    recent_risks: 'Останні фактори ризику',
    on_time: 'Вчасно',
    delayed: 'Затримка',
    status_resolved: 'ВИРІШЕНО',
    status_active: 'АКТИВНО',

    issue: 'Проблема',
    'Border Delay': 'Затримка на кордоні',
    'Customs Check': 'Митний контроль',
    'Vehicle Breakdown': 'Поломка транспорту',

    'All': 'Всі',
    'Medicine': 'Ліки',
    'Food': 'Продовольство',
    'Food Rations': 'Сухпайки',
    'Water': 'Вода',
    'Clean Water': 'Питна вода',
    'Generators': 'Генератори',
    'Ammunition': 'Амуніція',
    'Equipment': 'Обладнання',
    'Fuel': 'Паливо',
    'Thermal Blankets': 'Термоковдри',
    'Surgical Supplies': 'Хірургічне приладдя',
    'Other': 'Інше',

    'Normal': 'Стандартна',
    'High Priority': 'Високий пріоритет',
    'Critical Alert': 'Критична терміновість',

    'PENDING': 'ОЧІКУЄ',
    'IN_TRANSIT': 'В ДОРОЗІ',
    'DELIVERED': 'ДОСТАВЛЕНО',
    'DELAYED': 'ЗАТРИМКА',
    'DRAFT': 'ЧЕРНЕТКА',

    driver_view: 'Вид водія',
    current_route: 'Поточний маршрут',
    report_issue: 'Повідомити про проблему',
    mark_arrived: 'Позначити як прибув',

    create_order: 'Створити Замовлення',
    my_active_orders: 'Мої Активні Замовлення',
    live_supply_catalog: 'Каталог Припасів',
    select_items_to_start: 'Оберіть товари для конфігурації замовлення',
    search_catalog: 'Пошук в каталозі...',
    available_label: 'ДОСТУПНО',
    hub_label: 'ХАБ',
    empty_label: 'ПОРОЖНЬО',
    order_config: 'Конфігурація Замовлення',
    finalize_delivery: 'Завершити деталі доставки',
    please_select_item: 'Будь ласка, оберіть товар',
    click_any_card: 'Натисніть на будь-яку картку в каталозі, щоб почати',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('app_lang') || 'uk');
  const [theme, setTheme] = useState(() => localStorage.getItem('app_theme') || 'dark');

  useEffect(() => {
    if (theme === 'light') {
      document.body.classList.add('light-theme');
    } else {
      document.body.classList.remove('light-theme');
    }
  }, [theme]);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  }, [lang]);

  const changeLanguage = (v) => { setLang(v); localStorage.setItem('app_lang', v); };
  const changeTheme = (v) => { setTheme(v); localStorage.setItem('app_theme', v); };

  const value = useMemo(() => ({
    lang, changeLanguage,
    theme, changeTheme,
    t
  }), [lang, theme, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLang must be used within a LanguageProvider');
  }
  return context;
};